version: 2

sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: nations
      - name: regions
      - name: v_nations
      - name: parts
      - name: lineitems
      - name: suppliers
      - name: partsupps
      - name: orders
        config:
          freshness:
            warn_after: {count: 5, period: day}
            error_after: {count: 5, period: day}
          loaded_at_field: o_orderdate::timestamp_ntz

  - name: mkm
    database: mkmotors_dev
    schema: staging
    tables:
      - name: stg_employees

  - name: dw
    database: mkmotors_dev
    schema: dw
    tables:
      - name: dm_employees
